#!/usr/bin/env bash
# configures an ubuntu server to: localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8
sudo cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" | sudo tee -a ~/hosts.new
echo "8.8.8.8 facebook.com" | sudo tee -a ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
